# Generated by Django 5.0.7 on 2024-07-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_customuser_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_de_salle', models.CharField(max_length=100)),
                ('lieu', models.CharField(max_length=100)),
                ('capacite', models.CharField(max_length=100)),
                ('prix', models.CharField(max_length=50)),
                ('image', models.TextField()),
            ],
        ),
    ]
