# Generated by Django 5.0.7 on 2024-07-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_salle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_salle', models.CharField(max_length=10)),
                ('datedebut', models.DateTimeField()),
                ('datefin', models.DateTimeField()),
                ('id_user', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='salle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
