# Generated by Django 5.0.7 on 2024-07-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_salle_disponibilite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salle',
            name='disponibilite',
            field=models.BooleanField(default=True),
        ),
    ]
