# Generated by Django 5.0.6 on 2024-07-21 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_alter_salle_disponibilite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('Start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('capacity', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Salle',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='adresse',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='date_naissance',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='nom',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='prenom',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.customuser'),
        ),
        migrations.AddField(
            model_name='booking',
            name='id_salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.room'),
        ),
    ]
