# Generated by Django 5.0.6 on 2024-07-22 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_booking_room_delete_reservation_delete_salle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='id_salle',
            new_name='id_room',
        ),
    ]
