# Generated by Django 5.0.8 on 2024-08-11 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="id_room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="reservation.room",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="id_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="reservation.customuser",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="start_date",
            field=models.DateField(),
        ),
    ]
