# Generated by Django 5.0.8 on 2024-08-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0002_alter_booking_end_date_alter_booking_id_room_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
