# Generated by Django 5.0.8 on 2024-08-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0003_booking_is_cancelled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="image",
            field=models.ImageField(null=True, upload_to="images"),
        ),
    ]
