# Generated by Django 5.0.8 on 2024-08-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0004_alter_room_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
