# Generated by Django 5.0.8 on 2024-08-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0005_alter_room_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
