# Generated by Django 5.0.8 on 2024-09-03 10:05

from django.db import migrations

        
class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0007_alter_room_price"),
    ]

    operations = []
